### ISSUE TITLE
Build.rs panic: thread '<main>' panicked at 'LR1 TLS not installed'

### ISSUE THREAD

**Issue by brendanzab** [nikomatsakis/lalrpop#126] opened 2016-08-06 03:53 UTC
Here is a highly reduced example from my grammar:

```rust
grammar;

pub Expr: () = {
    "..." => (),
    <args: Expr> => (),
};
```

Full error with backtrace:

```
λ RUST_BACKTRACE=1 cargo build
   Compiling gluon_parser2 v0.1.2 (file:///Users/brendan/Desktop/gluon_test/parser)
error: failed to run custom build command for `gluon_parser2 v0.1.2 (file:///Users/brendan/Desktop/gluon_test/parser)`
Process didn't exit successfully: `/Users/brendan/Desktop/gluon_test/parser/target/debug/build/gluon_parser2-13841078bcd67f00/build-script-build` (exit code: 101)
--- stdout
processing file `/Users/brendan/Desktop/gluon_test/parser/src/grammar.lalrpop`

--- stderr
thread '<main>' panicked at 'LR1 TLS not installed', ../src/libcore/option.rs:699
stack backtrace:
   1:        0x10ddb535b - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:        0x10ddb7075 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:        0x10ddb6cae - std::panicking::default_hook::hf3839060ccbb8764
   4:        0x10ddaa517 - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:        0x10ddb7636 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:        0x10ddab3d8 - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:        0x10ddb728f - rust_begin_unwind
   8:        0x10dddd720 - core::panicking::panic_fmt::h93df64e7370b5253
   9:        0x10dde2965 - core::option::expect_failed::h03c4c03f58c1633f
  10:        0x10da25dff - _<std..option..Option<T>>::expect::h70db50e48534f6cd
  11:        0x10da2588c - lalrpop::lr1::tls::Lr1Tls::with::_$u7b$$u7b$closure$u7d$$u7d$::h886c634da239b835
  12:        0x10da25744 - _<std..thread..LocalKey<T>>::with::h23658747fb5bb4ef
  13:        0x10da25691 - lalrpop::lr1::tls::Lr1Tls::with::hc37abba8e516e004
  14:        0x10da25657 - lalrpop::lr1::lookahead::with::h52ca1f94dd9b806f
  15:        0x10da05d13 - lalrpop::lr1::lookahead::TokenSet::new::hf2a8242b860a271c
  16:        0x10da1dbf0 - lalrpop::lr1::first::FirstSets::first0::haccdc5dfd46769c3
  17:        0x10d971b85 - lalrpop::lr1::first::FirstSets::new::h7a22d65e67a752f7
  18:        0x10d9deb40 - lalrpop::lr1::error::ErrorReportingCx::new::h6311f531423a4b30
  19:        0x10d832266 - lalrpop::lr1::error::report_error::hf69e8e6de434504e
  20:        0x10d80772a - lalrpop::build::emit_recursive_ascent::h2a5bc907756b3aa8
  21:        0x10d7e2b3a - lalrpop::build::process_file_into::hd7cd0433837a0e61
  22:        0x10d7e1783 - lalrpop::build::process_file::h0a15575277e09bc9
  23:        0x10d7e4001 - lalrpop::build::process_dir::h4a3f7a542c213c85
  24:        0x10d7e39aa - lalrpop::api::Configuration::process_dir::h0b44072b06c48893
  25:        0x10d7e384f - lalrpop::api::Configuration::process_current_dir::hf05eb55c8a0a5df5
  26:        0x10d7e50f4 - lalrpop::api::process_root::h83b86c00729c989c
  27:        0x10d7dc250 - build_script_build::main::he5071e1b00fcfe0e
  28:        0x10ddb689d - std::panicking::try::call::hbbf4746cba890ca7
  29:        0x10ddb9ceb - __rust_try
  30:        0x10ddb9c85 - __rust_maybe_catch_panic
  31:        0x10ddb66c1 - std::rt::lang_start::hbcefdc316c2fbd45
  32:        0x10d7dc729 - main
```

**Comment by brendanzab** [comment] 2016-08-06 04:02
For some context, I am trying to do something like:

```rust
InfixExpr = {
    AppExpr,

    <e1: InfixExpr> <op: "BinOp"> <e2: AppExpr> =>
        Expr::BinOp(Box::new(e1), op.to_string(), Box::new(e2)),
};
```

Is there a problem with putting `InfixExpr` in itself, at the beginning of a rule?

**Comment by brendanzab** [comment] 2016-08-06 04:05
Hmm - seems like `pascal.lalrpop` does it: https://github.com/nikomatsakis/lalrpop/blob/master/doc/pascal/lalrpop/src/pascal.lalrpop#L49-L52

**Comment by brendanzab** [comment] 2016-08-06 08:48
So I figured out that it is probably just ambiguities in my grammar. Still, it probably could do with a better error!

**Comment by nikomatsakis** [comment] 2016-08-06 09:16
@brendanzab definitely! odd. I will investigate. :)

**Comment by CWood1** [comment] 2016-08-14 18:04
I just had the exact same error in my grammar. It only happens in 0.12.0. I've attached my grammar, the errors I get in 0.12.0, and the errors I get in 0.11.0 for context. It looks as though the issue is caused by grammar ambiguities, as far as I can tell (I started tracing the error through using the backtrace, and it does indeed go through error reporting code, so that makes sense).

[protdef.lalrpop.txt](https://github.com/nikomatsakis/lalrpop/files/417166/protdef.lalrpop.txt)
[error11.txt](https://github.com/nikomatsakis/lalrpop/files/417164/error11.txt)
[error12.txt](https://github.com/nikomatsakis/lalrpop/files/417165/error12.txt)

**Comment by nikomatsakis** [comment] 2016-08-15 18:37
Yeah, I'm seeing it too now, will try to fix shortly, should be an easy fix

**Comment by nikomatsakis** [comment] 2016-08-17 00:24
Should be fixed.

**Closed** 2016-08-17 00:23 UTC
