### ISSUE TITLE
Regex with "|" and "?" seems to break invariant

### ISSUE THREAD

**Issue by saghm** [nikomatsakis/lalrpop#101] opened 2016-03-04 00:39 UTC
I've come across a case where a certain regex I want to use as a terminal appears to break some internal invariant related to the underlying NFA. I've attempted to find the smallest possible regex that cases this issue, which is this:

```rust
Silly: String = {
    r"(1|0?)" => String::from(<>)
};
```

...which gives the following error:

```
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `NFA6`, right: `NFA3`)', /home/saghm/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/lalrpop-0.11.0/src/lexer/nfa/mod.rs:181
```

This problem doesn't appear to be symmetric, since when I change it to the following, it has no issues:

```rust
Silly: String = {
    r"(0?|1)" => String::from(<>)
};
```

Neither of these regular expressions seem to have any issue when passed as an argument to `Regex::new`, although from what I can tell, lalrpop seems to break down complex regexes rather than using them as-is, which could account for the different results in this case.

For reference, the regex that originally gave me this error is [this whopper](https://gmigdos.wordpress.com/2010/12/05/regular-expression-to-match-javascript-string-literals/) used to parse JavaScript string literals:

```
"([^\\"]+|\\([bfnrtv'"\\]|[0-3]?[0-7]{1,2}|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}))*"|'([^\\']+|\\([bfnrtv'"\\]|[0-3]?[0-7]{1,2}|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}))*'
```

**Comment by nikomatsakis** [comment] 2016-03-04 09:25
Interesting, thanks!

**Comment by frewsxcv** [comment] 2016-03-20 20:29
Seems like a duplicate of https://github.com/nikomatsakis/lalrpop/issues/97

**Closed** 2016-08-08 10:23 UTC
Labels: bug
