### ISSUE TITLE
Ambiguous strings in non-intersecting states are rejected

### ISSUE THREAD

**Issue by tfogal** [nikomatsakis/lalrpop#193] opened 2017-03-07 05:33 UTC
LALRPop complains about ambiguity even for terminals for which the ambiguity is resolved by the grammar:

```rust
grammar;

pub LEntry: () = {
  "1entry" <nm: LIdentifier> => {
    println!("got id {}!", nm);
  },
  "2nd-entry" <blah: LConstant> => {
    println!("2nd: got constant {}", blah);
  },
};

LIdentifier: String = {
  <id: r"[[:alpha:]]+[[:alnum:]]*"> => id,
};
LConstant: String = {
  <cons: r"[A-Z]+[A-Z0-9]*"> => cons,
};
```

LALRPop refuses to compile this grammar:

    /tmp/testlalrpop/src/ambiguous.lalrpop:13:7: 13:33 error: ambiguity detected between the terminal `r#"[[:alpha:]]+[[:alnum:]]*"#` and the terminal `r#"[A-Z]+[A-Z0-9]*"#`

Here the terminals are indeed ambiguous, but the ambiguity is a non-issue because the two terminals are not both available for shifting at any singular state.

**Comment by WilsonGiese** [comment] 2017-03-10 06:47
I just ran into this issue as well pretty quickly into writing a grammar... I think it can be resolved by writing a custom lexer, but it's not ideal. 

@nikomatsakis is this the expected behavior?

**Comment by nikomatsakis** [comment] 2017-03-15 10:40
This is indeed the expected behavior. LALRPOP, currently at least, follows the model of having a distinct lexer-parser phase. The lexer classifies the input into tokens **without knowing where in the grammar you are**, so there cannot be any overlap.

I have been contemplating trying to have LALRPOP adopt a non-standard model where the parser informs the lexer something about its state so that it can "narrow down" the range of tokens that are to be considered at any one point. As far as I know there is no precedent for that in other parser generators, but it seems feasible.

Another alternative would be to have LALRPOP support PEG-style parsing (#143); PEG grammars do not have a distinct lexing phase.

In general, though, the builtin lexer for LALRPOP was *intended* to be more of a toy, at least in its current state. I think any serious user would want to write their own. I had hoped to improve its capabilities in a number of ways but just haven't had much time for hacking on that. 

In any case, I'm going to close this issue for now as 'working as expected', but I'll open an issue to explore the idea of having the parser 'inform' the lexer of its current state.

**Closed by nikomatsakis** 2017-03-15 10:40 UTC
