### ISSUE TITLE
Comments with lalrpop

### ISSUE THREAD

**Issue by Ronaldho80** [nikomatsakis/lalrpop#149] opened 2016-09-28 14:04 UTC
What is the idiomatic way of providing comments for my grammar? I could not find anything in the docs and other examples besides writing my own lexer.

**Comment by BookOwl** [comment] 2017-03-28 23:32
@nikomatsakis, what is the status of specifying comments in the grammar? Writing an entire lexer just to add comments seems a bit overkill.

**Comment by BookOwl** [comment] 2017-04-03 20:27
bump

**Comment by nikomatsakis** [comment] 2017-04-03 20:32
@BookOwl see some thoughts towards the end of https://github.com/nikomatsakis/lalrpop/issues/10, which proposes a syntax; in fact, I'm going to close this issue as a duplicate of #10.

**Closed by nikomatsakis** 2017-04-03 20:32 UTC

**Comment by IreneKnapp** [comment] 2020-09-15 02:28
Hey, so, is there a recommended way to do this yet? Specifically, like @Ronaldho80, I am interested in writing comments *in my grammar* (to describe the grammar to my future self), not in writing a grammar which supports comments as one of the features.

I read through #10 but it seems to be about the necessary work to do that latter thing. I see how this is a prerequisite, since lalrpop is implemented in itself, but did anyone ever circle back and actually add comments to lalrpop itself? I read through https://github.com/lalrpop/lalrpop/blob/master/lalrpop/src/parser/lrgrammar.lalrpop and it looks like the answer is no?

**Comment by Marwes** [comment] 2020-09-15 08:22
@IreneKnapp It was implemented in https://github.com/lalrpop/lalrpop/pull/509

**Comment by Marwes** [comment] 2020-09-15 08:24
Or I guess you mean writing comments to describe the grammar? `//` and `/* */` work just fine there

**Comment by IreneKnapp** [comment] 2020-09-15 19:44
Ah! In that case, I have a bug to report. `//` does indeed work fine, thank you, and that solves my immediate problem. However, `/* */` gives me an "unrecognized token" error.

See below for my test files. This is with lalrpop 0.19.1. I'm happy to file this in a new issue if you prefer.

```
grammar;
                               
/* foo */
pub Filename: String = <filename:r"[\P{Z}&&\P{Co}&&\P{P}]+"> => filename.to_string();
```

```
12:41 Hanami:~/Projects/shell$ cargo build
   Compiling shell v0.1.0 (/home/irenes/Projects/shell)
error: failed to run custom build command for `shell v0.1.0 (/home/irenes/Projects/shell)`

Caused by:
  process didn't exit successfully: `/home/irenes/Projects/shell/target/debug/build/shell-3200bb2a7216635b/build-script-build` (exit code: 1)
--- stdout
processing file `/home/irenes/Projects/shell/src/commandline.lalrpop`
/home/irenes/Projects/shell/src/commandline.lalrpop:3:1: 3:1 error: unrecognized token

--- stderr
  /* foo */
  ^
```
