### ISSUE TITLE
we can reduce to a `Foo` but we can also shift

### ISSUE THREAD

**Issue by losvedir** [nikomatsakis/lalrpop#22] opened 2015-09-22 08:42 UTC
I'm trying to write a grammar along the lines of `parser.mly` in this [MiniML](http://andrej.com/plzoo/html/miniml.html) project. However, for the type recognition, I'm getting this error:

```
Process didn't exit successfully: `/...` (exit code: 1)
--- stdout
when in this state:
  Ty = Ty (*) "->" Ty [EOF]
  Ty = Ty (*) "->" Ty ["->"]
  Ty = Ty "->" Ty (*) [EOF]
  Ty = Ty "->" Ty (*) ["->"]
and looking at a token `"->"`,
we can reduce to a `Ty`
but we can also shift
```

My reduced case of the issue is as follows:

**ast.rs**
``` rust
#[derive(Debug)]
pub enum Type {
    Int,
    Bool,
    Arrow(Box<Type>, Box<Type>),
}
```

**lalrfail.lalrpop**
``` rust
use ast::Type;

grammar;

pub Ty: Type = {
    "int" => Type::Int,
    "bool" => Type::Bool,
    <t1:Ty> "->" <t2:Ty> => Type::Arrow(Box::new(t1), Box::new(t2)),
};
```

I believe this is what you mean in the tutorial when you say you aim to someday cover:

> Advice for resolving shift-reduce and reduce-reduce conflicts

but while the other TODO items at least have links to things I could explore to try to figure out on my own, I'm at a dead end here.

Until you have a chance to write that up, is there a small explanation somewhere of what's going on and maybe some high level tips for fixing it? If you can get me started, maybe I can figure it out for myself and then put something in the wiki about it, if you want.

**Comment by nikomatsakis** [comment] 2015-09-22 10:09
@losvedir

> I believe this is what you mean in the tutorial when you say you aim to someday cover:
>
> > Advice for resolving shift-reduce and reduce-reduce conflicts
>
> but while the other TODO items at least have links to things I could explore to try to figure out on my own, I'm at a dead end here.

Yes, that's exactly the kind of thing I plan to cover. This is
actually a really great example of a conflict though, thanks. (Both in
terms of something I should explain in the tutorial, and in terms of
something where I should see how to improve the error message.) The
problem you're encountering is that your grammar is ambiguous, and the
reason is because it does not indicate the associativity of the `->`
operator. In particular, given something like this:

    int -> int -> int

this could be parsed in two ways. It could either be left-associative:

    int -> int -> int
     |      |      |
     +------+      |
         |         |
        Ty         |
         |         |
         +---------+
              |
             Ty

or right-associativity (which is typically what you would expect for the `->` operator):

    int -> int -> int
     |      |      |
     |      +---+--+
     |          |
     |         Ty
     |          |
     +----------+
          |
         Ty
At least currently, you encode associativity in your grammar in a
similar way that you can encode precedence. The idea is that we want
to disallow an `->` from being on the LHS of another arrow, at least
without parentheses. So something like this:

```rust
pub Ty: Type = {
    Ty1,
    <t1:Ty1> "->" <t2:Ty> => Type::Arrow(Box::new(t1), Box::new(t2)),
};

pub Ty1: Type = {
    "int" => Type::Int,
    "bool" => Type::Bool,
    "(" <Ty> ")",
};
```

In terms of the error being reported, what it's saying is that (in its own charmingly opaque way) is that "if I have seen a `int -> int` and I see another `->`, I could either call the `int -> int` a `Ty` (reduce), or try to start another fn type using the second `int` (shift)". Anyway, it's kind of hard to explain the message without really diving into the hairy details of how the LR parser works internally, which is precisely why I want to investigate how to make a more "grammar-centric" error message here.

**Comment by nikomatsakis** [comment] 2015-09-22 10:12
I'm going to close this as a sub-item of the (more general) #23. Thanks!

**Comment by nikomatsakis** [comment] 2015-09-22 10:12
(But let me know if you still have any trouble here.)

**Closed by nikomatsakis** 2015-09-22 10:12 UTC

**Comment by losvedir** [comment] 2015-09-23 07:28
Aha! Crystal clear explanation, thanks. I guess that's what `%right TARROW` in `parser.mly` was for. (I don't know why I thought it would be a good idea to learn rust by implementing a language I don't know from the source code of a language I don't know, but here I am.) Anyway, that cleared up my confusion and your suggested fix did the trick. Thanks!

**Comment by timglabisch** [comment] 2016-01-20 23:30
I have the same problem and thanks to this issue i've got a first idea what's wrong.
I am trying to translate the php parser to rust:


```

pub expr : Box<Expression> = {
    <var:variable> => { Box::new(Expression::Variable(var)) },
    <expr:expr_without_variable> => { expr }
};

expr_without_variable : Box<Expression> = {
	<v1:variable> <op:T_PLUS_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
    <v1:variable> <op:T_MINUS_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
    <v1:variable> <op:T_MUL_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
// ....  
   <v1:variable> <op:T_DEC> => { Box::new(Expression::Decrement(v1, true)) },
    <op:T_INC> <v1:variable> => { Box::new(Expression::Increment(v1, false)) },
    <op:T_DEC> <v1:variable> => { Box::new(Expression::Decrement(v1, false)) },
    <expr_left:expr> <op:T_BOOLEAN_OR> <expr_right:expr> => { Box::new(Expression::ExpressionOp { op: op.to_string(), expr_left: expr_left, expr_right: expr_right }) }
```

will result in:

```
and looking at a token `"||"`,
we can reduce to a `expr_without_variable`
but we can also shift
```

as i learned in this thread the problem is that `<expr> <T_BOOLEAN_OR> <expr>`
is ambiguous. makes total sense because i never define in which expression is parsed first.

now i am not sure how to handle this case. the [php grammar](https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y#L856) defines a lot expressions here.

my first try was to duplicate the expression:

```
pub expr : Box<Expression> = {
    <var:variable> => { Box::new(Expression::Variable(var)) },
    <expr:expr_without_variable> => { expr }
};

pub expr_left : Box<Expression> = {
    <var:variable> => { Box::new(Expression::Variable(var)) },
    <expr:expr_without_variable_left> => { expr }
};

expr_without_variable_left : Box<Expression> = {
	<v1:variable> <op:T_PLUS_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
    <v1:variable> <op:T_MINUS_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
    <v1:variable> <op:T_MUL_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
   // ....
    <op:T_DEC> <v1:variable> => { Box::new(Expression::Decrement(v1, false)) }
};

expr_without_variable : Box<Expression> = {
	<v1:variable> <op:T_PLUS_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
    <v1:variable> <op:T_MINUS_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
    <v1:variable> <op:T_MUL_EQUAL> <expr:expr> => { Box::new(Expression::AssignOp { op: op.to_string(), var: v1, expr_right: expr }) },
    // ....
    <op:T_INC> <v1:variable> => { Box::new(Expression::Increment(v1, false)) },
    <op:T_DEC> <v1:variable> => { Box::new(Expression::Decrement(v1, false)) },
    <expr_left:expr_left> <op:T_BOOLEAN_OR> <expr_right:expr> => { Box::new(Expression::ExpressionOp { op: op.to_string(), expr_left: expr_left, expr_right: expr_right }) }
};
´´´

will result in 

```
and looking at a token `"||"`,
we can reduce to a `expr_left`
but we can also reduce to a `expr`
```

i don't really understand the error and i am not sure if this is the correct way.
now it should be clear that expr_left cannot contain a `T_BOOLEAN_OR` so it shouldn't be ambiguous?

the example above (`->`) looks quite easy but i am not fully sure that if i split `expr` to `expr_left` and `expr` that the result will be the same as the yacc %token grammar describe. is it? right now there is no smarter way than duplication everything for the left and the right side, or?

thanks for any help.

**Comment by timglabisch** [comment] 2016-01-22 21:36
i think i managed `%left`, but now i've issues with `%right` and have no idea how to tackle `%nonassoc`
 
example: https://github.com/timglabisch/rustphp/blob/e94ab2fe5d619146bc8cf54b0b7c23b5d058a2da/src/calculator1.lalrpop#L192

the code i want to rebuild: https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y#L72

**Comment by nikomatsakis** [comment] 2016-01-23 11:00
@timglabisch there is indeed a lot there in your example.

You can handle `%nonassoc` by having tiers like this:

```
EXPR = EXPR1 '==' EXPR1 | EXPR1 '!=' EXPR1
EXPR1 = // other kinds of expressions that don't include == and !=
...
EXPRN = '(' EXPR ')'
```

This will also make `==` and `!=` have lower precedence then the expressions in the EXPR1 category, and it will also fail to parse something like `x == y == z`, because you can't interpret `x == y` as an EXPR1, nor can you interpret `y == z` as an EXPR1. 

To handle `%right`, you want `x # y # z` (where `#` is some hypothetical right-associative operator) to parse like `x # (y # z)`, so you would set things up like so:

```
EXPR = EXPR1 '#' EXPR 
EXPR1 = // stuff that is not `#`
```

This way, `y # z` can only appear on the *right-hand-side* of a `#` (since it is part of `EXPR`, but not `EXPR1`).

Does that help?

**Comment by timglabisch** [comment] 2016-01-24 21:00
@nikomatsakis thanks a lot =) it tooked me a bunch of hours but finally i got that i don't have to define a left / right side. With "some kind of recursive parentheses" and "nesting the more important stuff" it works.

i build a small example https://github.com/timglabisch/shift_reduce_lalrpop/blob/master/src/main.rs#L11
that supports `%left`, `%right` and `%nonassoc`.

https://github.com/timglabisch/shift_reduce_lalrpop/blob/master/src/calculator1.lalrpop

**Comment by nikomatsakis** [comment] 2016-01-25 16:16
@timglabisch looks good, two questions:

First, on [this line](https://github.com/timglabisch/shift_reduce_lalrpop/blob/master/src/calculator1.lalrpop#L38) I suspect that you wanted `++` and `(` to be separate tokens (i.e., `"++" "("`, which is not equivalent.) I expect that should work fine, but it would allow you to parse `++ (x)` the same as `++(x)`.

Second, did you want `==` to be *non-associative*? In that case, I would expect `a == b == c` not to parse -- but you can achieve that fairly easily by changing from `expr == expr1` to `expr1 == expr1` [on this line](https://github.com/timglabisch/shift_reduce_lalrpop/blob/master/src/calculator1.lalrpop#L14). (Or am I misremembering what non-associative means?)

**Comment by timglabisch** [comment] 2016-01-25 22:34
thanks a lot! i (hopefully) finally fixed both issues.
