### ISSUE TITLE
Comma in a string in an action causes a parse error

### ISSUE THREAD

**Issue by dagit** [nikomatsakis/lalrpop#26] opened 2015-09-24 01:21 UTC
Take for example this grammar definition:

```
grammar;

pub a = {
  "a" => ","
};

pub aa = {
  "a" => "a"
};
```

```
src/a.lalrpop:8:12: 8:12 error: unterminated string literal; missing `"`?
    "a" => "a"
             ^
```

**Comment by nikomatsakis** [comment] 2015-09-24 08:24
This has the same root cause as #25, so I'm going to close it as a duplicate.

**Closed by nikomatsakis** 2015-09-24 08:24 UTC
