### ISSUE TITLE
Error recovery in 0.13 may end up in infinite loops

### ISSUE THREAD

**Issue by Marwes** [nikomatsakis/lalrpop#240] opened 2017-06-16 21:37 UTC
Tried to upgrade to 0.13.1 (from 0.12.5) but I have two tests for error recovery which now loops forever.

https://github.com/gluon-lang/gluon/blob/817d61eed462e27e196a7db6872ea57d801fd0ba/parser/tests/error_handling.rs#L64-L80

`cargo test --features test -p gluon_parser --test error_handling wrong_indent`

Looking at it in a debugger shows that after the `2` is received by lalrpop it will go into error recovery where after it will push a reduce action, evaluate it and then go right back into error recovery,

I am guessing this is to do with the lanetable implementation(?) breaking some assumption in the error recovery so I may may take a look over the weekend. I don't really have any guess as to why the lanetable would break it though so no promises that I know how to solve this!

**Comment by nikomatsakis** [comment] 2017-06-16 21:53
@Marwes you can disable the lane table by setting an environment variable -- that would verify your hypothesis -- but seems quite possible. I can take a look too, I have some thoughts as to what might be causing it.

**Comment by Marwes** [comment] 2017-06-16 21:58
Just ran `LALRPOP_LANE_TABLE=disabled cargo test --features test -p gluon_parser wrong_indent` and it does not loop forever.

**Comment by Marwes** [comment] 2017-06-17 14:16
Attempted to find a minimal reproduction and while I could not reproduce the infinite loop I think I found an example which fails due to the same problem.

https://github.com/Marwes/lalrpop/commit/6bf3a38c041545583cda1f640bc32f56a0f2f80c

Basically the `SkipExtraTokens` production do not skip tokens as I'd expect it to, instead the error recovery code thinks it can continue without dropping the `/` token after which it errors as normally or enters an infinite loop.

**Comment by nikomatsakis** [comment] 2017-06-22 13:06
@Marwes thanks! I have a theory as to the problem, but I haven't had time to investigate. I suspect it is due to the fact that the lane table loses the "minimal follow-set" property that LR(1) grammars typically have. In particular, at least the way I reconstructed it from the paper, it creates states that (initially) have a full follow-set, and then refines that 'on demand'. I *think* that when we do the "pop states until we find something that accepts the next terminal" step this causes us to pick a bad choice. I have to test this theory though.

**Comment by ivandardi** [comment] 2017-07-25 23:47
I can reproduce this. I tried running the `calculator6` example, and it never finishes parsing.

**Comment by nikomatsakis** [comment] 2017-08-29 09:52
@Marwes sorry for taking forever to investigate this -- I have a *possible* fix in #258. Would you mind giving it a spin and seeing if the problem still reproduces? (I'll also do some testing locally.)

@ivandardi same for you. =)

**Comment by Marwes** [comment] 2017-08-29 11:32
@nikomatsakis I tried gluon with #258 but it still loops forever :( will try my reproduction in https://github.com/nikomatsakis/lalrpop/issues/240#issuecomment-309217646 later today.

**Comment by nikomatsakis** [comment] 2017-08-30 09:34
@Marwes ok, thanks =) I figured it might not be that easy.

**Comment by Marwes** [comment] 2017-08-30 11:19
@nikomatsakis https://github.com/nikomatsakis/lalrpop/issues/240#issuecomment-309217646 works now, will try to dig up a new reproduction today or tomorrow.

**Comment by nikomatsakis** [comment] 2017-08-31 00:28
@Marwes ok, thanks

**Comment by nikomatsakis** [comment] 2017-09-11 08:38
@Marwes @ivandardi no pressure, but if you get a chance to try and reproduce the problems you saw, I'd appreciate it. I suppose I can issue a point release with the changes I've made thus far, as they seem to be strictly better than what came before, and it would make it mildly easier for you to test and try to reproduce.

**Comment by Marwes** [comment] 2017-09-11 09:05
@nikomatsakis Sorry, completely forgot about this. Hopefully I will manage before the end of this week after I deal with a bunch of other issues I got caught up in.

**Comment by nikomatsakis** [comment] 2017-09-11 23:59
@Marwes no worries, I'm the one who took like 3 months to respond to your initial issue report =)

**Comment by ivandardi** [comment] 2017-09-12 19:27
Sorry for taking a long time to respond! College's been killing me DX

I tried to reproduce it with the calculator6 example, and it runs ok now.
From what I remember, it wasn't looping forever when parsing, but rather
when generating the language file. I might be wrong about that. But as I
said, I can't get it to loop forever now.

I'll put error handling in my compiler again and if for some reason it
loops forever, I'll let you know!

**Comment by Marwes** [comment] 2017-09-13 19:42
@nikomatsakis 

https://github.com/Marwes/lalrpop/commit/e9d886651023fcd3c19ae96f88f0ec757993083a

Fresh reproduction of the infinite loop I am getting in gluon. If the `! => ...` production is removed then lalrpop errors out as normal, otherwise it loops forever.

**Comment by nikomatsakis** [comment] 2017-10-22 10:54
@Marwes thanks! Sorry for the delay again. I'll take a look. That said, @joerivanruth's commit is doing roughly the thing that I was contemplating doing!

**Comment by nikomatsakis** [comment] 2017-10-22 10:54
Er, never mind, I was perhaps a bit confused. =)

**Comment by nikomatsakis** [comment] 2017-10-22 12:29
So, I found the problem and fixed it in [the `issue-240` branch](https://github.com/nikomatsakis/lalrpop/tree/issue-240). But now I am hitting a (seemingly pre-existing) bug where error recover panics on that particular grammar -- something is popped off the stack with unexpected type. This occurs even with lane table disabled, if you add `#[LALR]` to the grammar declaration.

**Comment by nikomatsakis** [comment] 2017-10-22 14:49
OK, I think I see the erroneous path in the code. There are a couple of things going on here.

First, in the code as it is today, the stack of symbols and states can become misaligned. What can happen is that 

- we have to [pop one state because it does not accept `error`](https://github.com/nikomatsakis/lalrpop/blob/issue-240/lalrpop/src/lr1/codegen/parse_table.rs#L174)
- we then [proceed to this loop, which considers dropping tokens](https://github.com/nikomatsakis/lalrpop/blob/issue-240/lalrpop/src/lr1/codegen/parse_table.rs#L185)
- the [lookahead token is not accepted](https://github.com/nikomatsakis/lalrpop/blob/issue-240/lalrpop/src/lr1/codegen/parse_table.rs#L186)
    - and [hence we decide to drop it](https://github.com/nikomatsakis/lalrpop/blob/issue-240/lalrpop/src/lr1/codegen/parse_table.rs#L193)
        - but [we reach EOF](https://github.com/nikomatsakis/lalrpop/blob/issue-240/lalrpop/src/lr1/codegen/parse_table.rs#L195)
            - in which case we never [adjust the symbol stack, as we ought to](https://github.com/nikomatsakis/lalrpop/blob/issue-240/lalrpop/src/lr1/codegen/parse_table.rs#L188)

I *think* the fix for this is just to move that `truncate` call earlier. I'll give that a try.

But there's another question. I was reading up on error recovery and I see two general strategies described "in the literature". The one I believe we implemented is the one described in [these class notes](https://www.cs.clemson.edu/course/cpsc827/material/LRk/LR%20Error%20Recovery.pdf) (and iirc the one that YACC does):

- pop states until we find one that accepts error, then:
    - drop input tokens until we find one that this state accepts, then:
        - push error

But the other algorithm, described e.g. in [LR1 Parser Generation System: LR1 Error Recovery, Oracles, and Generic Tokens](https://arxiv.org/pdf/1010.1234.pdf), works slightly differently:

- Scan the stack to see if it contains a state X where:
    - X accepts error, transitioning to the state Y
    - and state Y accepts the current token
- If so, we pop to state X, push error, and then continue. Y should now be accepted.
- Otherwise, we drop the current token, and then go back to the first step and try again.

These seem very similar but slightly different. For example, the current algorithm might commit early to an error recovery point that forces us to drop a lot of input tokens -- maybe all the remaining tokens. @Marwes do you remember if there's a reason you opted for the current algorithm in particular?

**Comment by Marwes** [comment] 2017-10-22 15:07
I do remember reading https://arxiv.org/pdf/1010.1234.pdf but I must have missed the distinction between those two algorithms. Honestly the main reason I implemented the first method was that I found the found the third link in https://github.com/nikomatsakis/lalrpop/pull/160  to explain the algorithm the best.

**Comment by Storyyeller** [comment] 2018-01-01 21:24
I just ran into this issue while attempting to run Gluon with tip of tree LALRPOP.

Gluon's parser tests pass prior to b1d1d93, but are broken on every commit I tried after that. It seems that lane tables broken something and the workarounds aren't working.

**Comment by Marwes** [comment] 2018-01-01 21:36
@Storyyeller Gluon should still work as long as lane tables are disabled (which is done in the build script) https://github.com/gluon-lang/gluon/blob/c450475fdca856580a6ec9a6854e0d5352eceb9e/parser/build.rs#L4 . Are you trying to disable that?

**Comment by Storyyeller** [comment] 2018-01-01 21:49
Oh, I see. I accidentally got rid of that. It does work with lane tables disabled.

**Comment by nikomatsakis** [comment] 2018-01-19 09:29
BTW I've been super distracted by the Rust impl period, but I'm finally getting back to this now. I hope to have a fix up for this issue and a new release of LALRPOP soon.

**Closed** 2018-01-24 09:18 UTC
